"""
直观解释为什么 R 循环会产生 switch
"""

print('=' * 80)
print('为什么 R 循环会产生 switch？')
print('=' * 80)
print()

print('【关键理解】')
print('R 循环改变的是 H 坐标，不改变 W 坐标')
print()

print('=' * 80)
print('【w_only: 每次都要「跳回」起点】')
print('=' * 80)
print()

print('w_only tile (q=3): W 范围 = [24, 31]，跨越 block 边界')
print()
print('想象一个横向的读取过程:')
print()
print('    W 坐标:    0 ─────────────────── 31 ─────────────────── 62')
print('               │      block 0       │       block 1        │')
print('               │                    │                      │')
print('               │        ┌───────────┼───┐                  │')
print('               │        │ tile 范围 │   │                  │')
print('               │        │ W=[24,31] │   │                  │')
print('               │        └───────────┴───┘                  │')
print('                        ↑               ↑')
print('                        24              31')
print()

print('每次访问这个 tile，都是从左到右读取:')
print()
print('  r=0:  [ W=24 ────────→ W=31 ]')
print('        start(block 0)   end(block 1)')
print()
print('  r=1:  [ W=24 ────────→ W=31 ]  <-- 又从 W=24 重新开始')
print('        start(block 0)   end(block 1)')
print()
print('  r=2:  [ W=24 ────────→ W=31 ]  <-- 又从 W=24 重新开始')
print('        ...')
print()

print('问题:')
print('  - r=0 结束在 block 1 (W=31)')
print('  - r=1 开始在 block 0 (W=24)')
print('  - 需要从 block 1 跳回 block 0 => row activation!')
print()

print('R 循环改变的是 H，不影响 W')
print('所以 W 方向的读取模式每次都一样: 从 24 到 31')
print('每次都要「重走」这段路，都要经历 block 0 → block 1')
print()

print('=' * 80)
print('【h_only: 自然衔接，不需要跳回】')
print('=' * 80)
print()

print('h_only tile (p=15): H 范围 = [30, 31]，跨越 block 边界')
print()
print('    H 坐标:')
print('    ')
print('    28  │')
print('    29  │  block 0')
print('    30  │ ←── tile start')
print('    ────┼────────────── block 边界')
print('    31  │ ←── tile end')
print('    32  │')
print('    33  │  block 1')
print('    ...')
print()

print('R 循环改变 H:')
print()
print('  r=0: H=[30,31], 跨越边界')
print('       start=H=30 (block 0), end=H=31 (block 1)')
print()
print('  r=1: H=[31,32], 完全在 block 1 内')
print('       start=H=31 (block 1)')
print()
print('关键:')
print('  - r=0 结束在 H=31 (block 1)')
print('  - r=1 开始在 H=31 (block 1)')  
print('  - 衔接! 不需要跳回!')
print()

print('R 循环改变 H，所以:')
print('  - r=0 结束的位置 (H=31) 正好是 r=1 开始的位置')
print('  - 自然连续，不产生 switch')
print()

print('=' * 80)
print('【核心区别】')
print('=' * 80)
print()
print('┌────────────────────────────────────────────────────────────────────┐')
print('│  类型   │ 跨越方向 │ R循环影响 │     结果                         │')
print('├─────────┼──────────┼───────────┼──────────────────────────────────┤')
print('│ h_only  │    H     │  改变H    │ 衔接: prev.end ≈ curr.start      │')
print('│         │          │           │ 不需要跳回                        │')
print('├─────────┼──────────┼───────────┼──────────────────────────────────┤')
print('│ w_only  │    W     │  不影响W  │ 不衔接: prev.end 在 W_max        │')
print('│         │          │           │ curr.start 在 W_min，需要跳回    │')
print('└─────────┴──────────┴───────────┴──────────────────────────────────┘')
print()

print('简单说:')
print('  h_only + R循环 = H方向连续 = 衔接 = 少switch')
print('  w_only + R循环 = W方向重复 = 每次跳回 = 多switch')
